# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0002_auto_20170620_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='perm',
            name='name',
            field=models.CharField(default='asdf', max_length=64, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
