# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0003_perm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='perm',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
