# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hostname',
            field=models.CharField(default='a', max_length=128, unique=True, verbose_name='Hostname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP'),
        ),
    ]
