# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perm',
            name='comment',
            field=models.CharField(default='test', max_length=100, verbose_name='备注'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perm',
            name='name',
            field=models.CharField(default='test', max_length=100, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
