# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0002_auto_20161210_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perm',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
    ]
