# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0003_auto_20161210_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perm',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
    ]
